### ISSUE TITLE
Comando Sobremim ou Aboutme está com Problemas!

### ISSUE THREAD

**Issue by TiaGoiNsaNy** [BotFoxy/Foxy#56]
# :question: Problemas no Sobremim:

:thinking: Vi que não possui um limite de caracteriais no comando, é bem simples de resolver, apenas adicione uma simples condição abaixo:

```javascript
if (message.content.length > <Number>) {
    return message.channel.send();
};
```

# :rainbow_flag: WinG4merBR é MUITO GAY! KKKKKK

**Comment by zEneeergy** [comment]
@WinG4merBR eu acho que 255 caracteres eh um bom limite, e também gostaria de informar q eu vou voltar a ajudar com a foxy quando chegar o meu SSD

**Comment by WinG4merBR** [comment]
Então tia, eu esqueci de adicionar aviso de sem argumentos mas acabei de fazer um push com essa alteração

**Comment by TiaGoiNsaNy** [comment]
## :+1: Tudo bem meu prostituto :heart:!
