### ISSUE TITLE
Problemas sobre o f!background

### ISSUE THREAD

**Issue by JayTheD3veloper** [BotFoxy/Foxy#67]
owo ciao!

então o  background e quase ou totalmente hardcoded que e mei ruim caso você queira ocultar / diferenciar background já comprados para evitar pessoas com amnesia ou até mesmo dificulta a criação de novos backgrounds :( (nescessitando da reinicialização do bot)

eu sugiro cirar um "Model" (se isso pode ser chamado assim) melhor : uma base para background que nem tem para comandos exemplo (se o json fico ruim disculpa):
```JSON
{
 "Name":"Mamaconha",
 "Code":"conha",
 "Value":182701,
 "Rarity":"Rare",
 "Image":"cannabis.png",
 "Example":"exemplos/maconha.png" //Edit eu esqueci isso
}
```
na listagem poderia ser algo como:
```js
var linha_dos_bgs = "";
for ( bg in backgrounds ) linha_dos_bgs += `(${bg.Rarity}) **${bg.Name}** - ${bg.Value} FoxCoins - **Código:**{$.bg.Code}\n`;
```
e se quiser diferenciar o background atual:
```js
var linha_dos_bgs = "";
for ( bg in backgrounds ) {
   if (user.bg != bg) {
    linha_dos_bgs += `(${bg.Rarity}) **${bg.Name}** - ${bg.Value} FoxCoins - **Código:**{$.bg.Code}\n`;
  }
  else {
  linha_dos_bgs += `(${bg.Rarity}) **${bg.Name}** - Comprado - **Código:**{$.bg.Code}\n`;
  }
}
```
Edit: **Ja que todo mundo ama aquele bentido quadrado amarelo eu portei os exemplos**

**Comment by Rafae1CM** [comment]
Faz muito sentido não, você salvar em uma database, ou um json, os backgrounds, pois na verdade ainda nem implementamos sistemas de trocas, etc. Então nesse momento não é necessário fazer isso.

**Comment by zEneeergy** [comment]
Na verdade pode ser bom sim, você viu o código do f!background, é de dar vontade de vomitar

**Comment by zEneeergy** [comment]
E não sei se você entendeu a proposta do @JayTheD3veloper corretamente, ele de forma bem básica quer facilitar a nossa vida ao adicionar novos backgrounds

**Comment by zEneeergy** [comment]
[Feature implementada!](https://github.com/BotFoxy/Foxy/commit/a16c39386e968993595cafbaa280d14119537563)
